x-app_environment: &app_environment
  environment:
    # Postgress
    - POSTGRES_HOST
    - POSTGRES_PORT
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB

# x-app_environment: &app_environment
#   environment:
#     # Postgres
#     - POSTGRES_USER
#     - POSTGRES_PASSWORD
#     - POSTGRES_HOST
#     - POSTGRES_PORT
#     - POSTGRES_NAME
#     # Telebot
#     - BOT_TOKEN
#     # SQLAlchemy
#     - SQLA_ECHO

services:
  db:
    restart: unless-stopped
    image: postgres:18.1-alpine3.23
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgresdata:/var/lib/postgresql/
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  postgresdata:

  # app:
  #   restart: always
  #   build:
  #     context: ./app
  #   command: sh -c "python wait-for &&
  #                   alembic upgrade head &&
  #                   python main.py"
  #   volumes:
  #     - ./app:/app
  #   <<: *app_environment
