"""add notification row

Revision ID: 232017c3ff8f
Revises: f7f0ad06ed51
Create Date: 2024-09-09 11:15:22.519543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232017c3ff8f'
down_revision: Union[str, None] = 'f7f0ad06ed51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_tasks', sa.Column('notification', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_tasks', 'notification')
    # ### end Alembic commands ###
